"""Initial tables: User and Owner

Revision ID: 646bb4c0a5e9
Revises: 
Create Date: 2025-11-14 16:13:02.167327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '646bb4c0a5e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('dni', sa.String(length=8), nullable=False),
    sa.Column('celular', sa.String(length=9), nullable=True),
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('sexo', sa.String(length=20), nullable=True),
    sa.Column('fechaNacimiento', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('dni')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('asistente', 'veterinario', name='user_roles'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('owners')
    # ### end Alembic commands ###
